"""Render a CTDCheckResult as a Markdown gap report.

This is the *structured* report. IBM Bob (via the MCP server) takes the same result and
writes the narrative version — recommended remediation order, who to chase, etc.
"""

from __future__ import annotations

from pharos.ctd.checker import CTDCheckResult

SEVERITY_ICON = {"critical": "🔴", "major": "🟠", "minor": "🟡"}


def _bar(score: float, width: int = 20) -> str:
    filled = int(round(score * width))
    return "█" * filled + "░" * (width - filled)


def gap_report_markdown(result: CTDCheckResult) -> str:
    lines: list[str] = []
    verdict = "✅ READY TO SUBMIT — no required-section gaps" if result.ready_to_submit else "❌ NOT READY — required sections missing or in draft"
    lines += [
        f"# CTD Submission Readiness — {result.product}",
        "",
        f"**Region:** {result.region}  ·  **Checklist:** {result.spec_version}",
        "",
        f"## Verdict: {verdict}",
        "",
        f"**Overall completeness:** {result.overall_score * 100:.1f}%  `{_bar(result.overall_score)}`",
        "",
        "## Completeness by module",
        "",
        "| Module | Title | Score | Required present | Draft | Gaps |",
        "|---|---|---|---|---|---|",
    ]
    for m in result.modules:
        lines.append(
            f"| {m.module_id} | {m.title} | {m.score * 100:.0f}% `{_bar(m.score, 10)}` | "
            f"{m.required_present}/{m.required_total} | {m.required_draft} | {len(m.gaps)} |"
        )

    lines += ["", "## Gaps (required sections), most severe first", ""]
    if not result.gaps:
        lines.append("_None._")
    else:
        lines += ["| Sev | Section | Title | Status | Why it matters |", "|---|---|---|---|---|"]
        for g in result.gaps:
            lines.append(
                f"| {SEVERITY_ICON[g.severity]} {g.severity} | {g.section_id} | {g.title} | {g.status} | {g.note or '—'} |"
            )

    optional = [(m.module_id, o) for m in result.modules for o in m.optional_missing]
    if optional:
        lines += ["", "## Optional / conditional sections not present (informational)", ""]
        for mid, o in optional:
            lines.append(f"- Module {mid}: {o}")

    if result.warnings:
        lines += ["", "## Warnings", ""]
        lines += [f"- {w}" for w in result.warnings]

    if result.unmatched_entries:
        lines += ["", "## Outline entries not recognised as CTD sections", ""]
        lines += [f"- {u}" for u in result.unmatched_entries]

    lines += [
        "",
        "---",
        "_Generated by Pharos. Severity: critical = rejection-grade if missing; major = will draw a deficiency letter; "
        "minor = administrative/navigational. Checklist encodes ICH M4(R4); regional Module 1 content is simplified — "
        "confirm against the current agency guidance._",
    ]
    return "\n".join(lines)
